name: "auto-deploy"


env:
  CLOUDFLARE_API_TOKEN: ALElTeQPvQv0nqoKjYZVNG9D4-5DJRw8tCXwJ8BO
  CLOUDFLARE_ACCOUNT_ID: d7645b73787ae3d6eb140571ae7e64cb

on:
  push:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: eslint .

  deploy-stg:
    runs-on: "ubuntu-20.04"
    needs: ["lint"]
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      
      - name: "Install wrangler"
        run: "npm install wrangler -g"

      - name: "Publish (not main)"
        run: "echo deploying to stging"
  
  deploy-prd:
    runs-on: "ubuntu-20.04"
    needs: ["lint"]
    steps:
      - name: "Deploy to prd"
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ololyas
          minimum-approvals: 1
          issue-title: "Deploy to PROD env"
          issue-body: "Please approve or deny the deployment."
      - name: "Deploy to PROD env"
        run: "make deploy"
      