name: "auto-deploy"

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

# env:
#   CLOUDFLARE_API_TOKEN: ALElTeQPvQv0nqoKjYZVNG9D4-5DJRw8tCXwJ8BO
#   CLOUDFLARE_ACCOUNT_ID: d7645b73787ae3d6eb140571ae7e64cb

on:
  push:
    branches:
      - main

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          
      - name: Deploy to STG env
        run: make deploy STACK=stg

      - name: Deploy to PROD env
        run: make deploy STACK=prd

